#!/bin/zsh

mkdir $HOME/.config/alacritty
mkdir $HOME/.config/nvim
mkdir $HOME/.config/kanata

ln -s $PWD/aerospace/.aerospace.toml $HOME/.aerospace.toml
ln -s $PWD/tmux/.tmux.conf $HOME/.tmux.conf
ln -s $PWD/zsh/.zshrc $HOME/.zshrc
touch $HOME/.zsh_config
ln -s $PWD/git/.gitconfig $HOME/.gitconfig
ln -s $PWD/alacritty/alacritty.toml $HOME/.config/alacritty/alacritty.toml
ln -s $PWD/nvim/init.lua $HOME/.config/nvim/init.lua
ln -s $PWD/kanata/kanata.kbd $HOME/.config/kanata/kanata.kbd

# Replace $HOME with the expansion of $HOME
sed "s#\$HOME#$HOME#g" kanata/com.example.kanata.plist > ~/.config/kanata/com.example.kanata.plist
